env:
  - CGO_ENABLED=0
  - REPO_OWNER=solarwinds
  - REPO_NAME=swo-cli
builds:
  - main: ./cmd/swo/main.go
    id: "linux"
    binary: swo
    ldflags:
      - "-s -w -X 'main.version=v{{ .Version }}'"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
#      - windows_amd64
  - main: ./cmd/swo/main.go
    id: "win"
    binary: swo
    ldflags:
      - "-s -w -X 'main.version=v{{ .Version }}'"
    targets:
#      - darwin_amd64
#      - darwin_arm64
#      - linux_amd64
#      - linux_arm64
      - windows_amd64
archives:
  - id: zip
    builds:
      - win
      - linux
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: zip

universal_binaries:
  - replace: true
    name_template: "swo"

changelog:
  disable: true

checksum:
#  ids:
#    - linux
#    - win
  disable: false
  split: false
  name_template: '{{ .ProjectName }}_checksums.txt'

signs:
  - ids:
      - win
    artifacts: binary
    cmd: pwsh
    args:
      - "-c"
      - "Submit-SigningRequest -ApiToken '$CI_USER_TOKEN' -OrganizationId '$ORGANIZATION_ID' -ProjectSlug '$PROJECT' -SigningPolicySlug '$SIGNING_POLICY' -ArtifactConfigurationSlug '$ARTIFACT_CONFIGURATION' -InputArtifactPath '${artifact}' -OutputArtifactPath '${signature}' -WaitForCompletion"
    output: true